//Rate

export const POST_RATE_1O_MOVIES_PROCESS = "POST_RATE_1O_MOVIES_PROCESS";
export const POST_RATE_10_MOVIES_SUCCESS = "POST_RATE_10_MOVIES_SUCCESS";
export const POST_RATE_10_MOVIES_ERROR = "POST_RATE_10_MOVIES_ERROR";

export const POST_10_MOVIES_PROCESS = "POST_10_MOVIES_PROCESS";
export const POST_10_MOVIES_SUCCESS = "POST_10_MOVIES_SUCCESS";
export const POST_10_MOVIES_ERROR = "POST_10_MOVIES_ERROR";

export const GET_1O_MOVIES_RECOMENDATIONS_PROCESS =
	"GET_1O_MOVIES_RECOMENDATIONS_PROCESS";
export const GET_10_MOVIES_RECOMENDATIONS_SUCCESS =
	"GET_10_MOVIES_RECOMENDATIONS_SUCCES";
export const GET_10_MOVIES_RECOMENDATIONS_ERROR =
	"GET_10_MOVIES_RECOMENDATIONS_ERROR";

export const SEARCH_MOVIES_BY_NAME_PROCESS = "SEARCH_MOVIES_BY_NAME_PROCESS";
export const SEARCH_MOVIES_BY_NAME_SUCCESS = "SEARCH_MOVIES_BY_NAME_SUCCESS";
export const SEARCH_MOVIES_BY_NAME_ERROR = "SEARCH_MOVIES_BY_NAME_ERROR";
