# Generated by Django 5.0.3 on 2024-04-09 01:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_alumnos_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
