# Generated by Django 5.0.4 on 2024-05-03 04:07

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alumno_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='knownMovies',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('peliculas', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('idPelicula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('presupuesto', models.IntegerField()),
                ('votecount', models.IntegerField()),
                ('generos', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='unknownMovies',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('peliculas', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userLikes',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('peliculas', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
