# Generated by Django 5.0.4 on 2024-05-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_knownmovies_pelicula_unknownmovies_user_userlikes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unknownMovies',
            new_name='knownMovie',
        ),
        migrations.RenameModel(
            old_name='knownMovies',
            new_name='unknownMovie',
        ),
        migrations.RenameModel(
            old_name='userLikes',
            new_name='userLike',
        ),
    ]
