# Generated by Django 5.0.4 on 2024-05-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_gridview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridview',
            name='idUser',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='knownmovie',
            name='idUser',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unknownmovie',
            name='idUser',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='idUser',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
