//Rate

export const POST_RATE_1O_MOVIES_PROCESS = "POST_RATE_1O_MOVIES_PROCESS";
export const POST_RATE_10_MOVIES_SUCCESS = "POST_RATE_10_MOVIES_SUCCESS";
export const POST_RATE_10_MOVIES_ERROR = "POST_RATE_10_MOVIES_ERROR";

export const POST_10_MOVIES_PROCESS = "POST_10_MOVIES_PROCESS";
export const POST_10_MOVIES_SUCCESS = "POST_10_MOVIES_SUCCESS";
export const POST_10_MOVIES_ERROR = "POST_10_MOVIES_ERROR";
