// Register
export const POST_REGISTER_USER_PROCESS = "POST_REGISTER_USER_PROCESS";
export const POST_REGISTER_USER_SUCCESS = "POST_REGISTER_USER_SUCCESS";
export const POST_REGISTER_USER_ERROR = "POST_REGISTER_USER_ERROR";
//Login
export const POST_LOGIN_USER_PROCESS = "POST_LOGIN_USER_PROCESS";
export const POST_LOGIN_USER_SUCCESS = "POST_LOGIN_USER_SUCCESS";
export const POST_LOGIN_USER_ERROR = "POST_LOGIN_USER_ERROR";
//logout
export const USER_LOGOUT = "USER_LOGOUT";
